import { promises as fs } from 'fs';
import { exec } from 'child_process';
import { promisify } from 'util';
import { config } from '../config/env.js';
import { logger } from '../utils/logger.js';

const execAsync = promisify(exec);

export const nginxEngine = {
  async generateConfig(
    domain: string,
    internalPort: number,
    deploymentId: string
  ): Promise<string> {
    return `
# Auto-generated Nginx config for Flame Core
# Deployment: ${deploymentId}
# Generated: ${new Date().toISOString()}

server {
    listen 80;
    listen [::]:80;
    server_name ${domain};

    # Redirect HTTP to HTTPS
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ${domain};

    # SSL certificates (will be generated by Certbot)
    ssl_certificate /etc/letsencrypt/live/${domain}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${domain}/privkey.pem;

    # SSL configuration
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

    # Security headers
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;

    # Reverse proxy to Docker container
    location / {
        proxy_pass http://localhost:${internalPort};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;

        # Timeouts
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }

    # Logging
    access_log /var/log/nginx/flame-${deploymentId}-access.log;
    error_log /var/log/nginx/flame-${deploymentId}-error.log;
}
`;
  },

  async createSiteConfig(
    domain: string,
    internalPort: number,
    deploymentId: string
  ): Promise<{ success: boolean; configPath?: string; error?: string }> {
    try {
      logger.info('Creating Nginx config', { domain, internalPort });

      const configContent = await this.generateConfig(domain, internalPort, deploymentId);
      const configFileName = `flame-${domain.replace(/\./g, '-')}`;
      const configPath = `${config.deployment.nginxSitesAvailable}/${configFileName}`;

      // Write config file
      await fs.writeFile(configPath, configContent);
      logger.info('Config file written', { configPath });

      // Create symlink to sites-enabled
      const enabledPath = `${config.deployment.nginxSitesEnabled}/${configFileName}`;
      try {
        await fs.unlink(enabledPath);
      } catch {
        // symlink doesn't exist yet
      }

      await fs.symlink(configPath, enabledPath);
      logger.info('Symlink created', { enabledPath });

      // Test Nginx config
      const { stdout, stderr } = await execAsync('nginx -t');
      if (stderr && stderr.includes('error')) {
        return { success: false, error: stderr };
      }

      // Reload Nginx
      await execAsync('systemctl reload nginx');
      logger.info('Nginx reloaded');

      return { success: true, configPath };
    } catch (error: any) {
      logger.error('Create site config failed', error);
      return { success: false, error: error.message };
    }
  },

  async enableSSL(
    domain: string
  ): Promise<{ success: boolean; error?: string }> {
    try {
      logger.info('Enabling SSL with Certbot', { domain });

      // Run Certbot
      const { stdout, stderr } = await execAsync(
        `certbot --nginx -d ${domain} --non-interactive --agree-tos --email admin@flamecore.ng --expand`
      );

      if (stderr && stderr.includes('Error')) {
        return { success: false, error: stderr };
      }

      logger.info('SSL certificate created', { domain });

      // Reload Nginx to apply SSL
      await execAsync('systemctl reload nginx');

      return { success: true };
    } catch (error: any) {
      logger.error('Enable SSL failed', error);
      return { success: false, error: error.message };
    }
  },

  async removeSiteConfig(domain: string): Promise<{ success: boolean; error?: string }> {
    try {
      logger.info('Removing Nginx config', { domain });

      const configFileName = `flame-${domain.replace(/\./g, '-')}`;
      const configPath = `${config.deployment.nginxSitesAvailable}/${configFileName}`;
      const enabledPath = `${config.deployment.nginxSitesEnabled}/${configFileName}`;

      // Remove symlink
      try {
        await fs.unlink(enabledPath);
      } catch {
        // Already removed
      }

      // Remove config file
      try {
        await fs.unlink(configPath);
      } catch {
        // Already removed
      }

      // Reload Nginx
      await execAsync('systemctl reload nginx');
      logger.info('Site removed and Nginx reloaded');

      return { success: true };
    } catch (error: any) {
      logger.error('Remove site config failed', error);
      return { success: false, error: error.message };
    }
  },
};
